database_in=file:/var/lib/aide/defense-in-depth.db.gz
database_out=file:/var/lib/aide/defense-in-depth.db.new.gz
gzip_dbout=yes
report_url=stdout

DID=p+i+n+u+g+s+m+c+sha256

/etc/ssh DID
/opt/defense-in-depth/monitored DID
